name: Checks and tests units

on:
  pull_request:
    branches:
      - main

jobs:
  on-pull-request-check-and-tests:
    runs-on: ubuntu-latest

    steps:
    - name: â†ªï¸ Checkout code
      uses: actions/checkout@v4

    - name: ğŸª¢ Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: ğŸ“¦ Install dependencies
      run: yarn install

    - name: ğŸ” Check type
      run: yarn type
      
    - name: ğŸ§¼ Check lint
      run: yarn lint

    - name: ğŸ”¥ Check deadcode
      run: yarn deadcode

    - name: ğŸ§ª Run tests units
      run: yarn test

